server:
  port: 9002
spring:
  application:
    name: SERVICE-PRODUCT
#全部追踪1
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
