server:
  port: 9011
spring:
  application:
    name: FEIGN-ORDER
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  hystrix:
    enabled: true

# 仪表盘配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
